export const PHOTO_LINK = "PHOTO_LINK";
export const PHOTO_LINK_REQUEST = "PHOTO_LINK_REQUEST";
export const LOAD_INVESTIGATOR_INFO_REQUEST = "LOAD_INVESTIGATOR_INFO_REQUEST";
export const LOAD_INVESTIGATOR_INFO_ERROR = "LOAD_INVESTIGATOR_INFO_ERROR";
export const LOAD_INVESTIGATOR_INFO = "LOAD_INVESTIGATOR_INFO";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";