export const LOAD_CASE_INFO_REQUEST = "LOAD_CASE_INFO_REQUEST";
export const LOAD_CASE_INFO_ERROR = "LOAD_CASE_INFO_ERROR";
export const LOAD_CASE_INFO_SUCCESS = "LOAD_CASE_INFO_SUCCESS";

export const LOAD_SECTIONS_REQUEST = "LOAD_SECTIONS_REQUEST";
export const LOAD_SECTIONS_ERROR = "LOAD_SECTIONS_ERROR";
export const LOAD_SECTIONS_SUCCESS = "LOAD_SECTIONS_SUCCESS";
export const LOAD_SELECTED_SECTION = "LOAD_SELECTED_SECTION";

export const EDIT_SECTION_REQUEST = "EDIT_SECTION_REQUEST";
export const EDIT_SECTION_SUCCESS = "EDIT_SECTION_SUCCESS";
export const EDIT_SECTION_ERROR = "EDIT_SECTION_ERROR";

export const DELETE_SECTION_REQUEST = "DELETE_SECTION_REQUEST";
export const DELETE_SECTION_SUCCESS = "DELETE_SECTION_SUCCESS";
export const DELETE_SECTION_ERROR = "DELETE_SECTION_ERROR";

export const DOWNLOAD_REPORT_REQUEST = "DOWNLOAD_REPORT_REQUEST";
export const DOWNLOAD_REPORT_SUCCESS = "DOWNLOAD_REPORT_SUCCESS";
export const DOWNLOAD_REPORT_ERROR = "DOWNLOAD_REPORT_ERROR";

export const RESET_EDIT_STATE = "RESET_EDIT_STATE";
