export const CREATE_NEW_SECTION_REQUEST = "CREATE_NEW_SECTION_REQUEST";
export const CREATE_NEW_SECTION_SUCCESS = "CREATE_NEW_SECTION_SUCCESS";
export const CREATE_NEW_SECTION_ERROR = "CREATE_NEW_SECTION_ERROR";