export const EDIT_CLIENT_REQUEST = "EDIT_CLIENT_REQUEST";
export const EDIT_CLIENT_SUCCESS = "EDIT_CLIENT_SUCCESS";
export const EDIT_CLIENT_ERROR = "EDIT_CLIENT_ERROR";

export const CHANGE_CLIENT_FIRST_NAME = "CHANGE_CLIENT_FIRST_NAME";
export const CHANGE_CLIENT_LAST_NAME = "CHANGE_CLIENT_LAST_NAME";
export const CHANGE_CLIENT_USERNAME = "CHANGE_CLIENT_USERNAME";
export const CHANGE_CLIENT_EMAIL = "CHANGE_CLIENT_EMAIL";
export const CHANGE_CLIENT_PASSWORD = "CHANGE_CLIENT_PASSWORD";

export const CHANGE_CLIENT_POINT_OF_CONTACT_NAME = "CHANGE_CLIENT_POINT_OF_CONTACT_NAME";
export const CHANGE_CLIENT_POINT_OF_CONTACT_PHONE = "CHANGE_CLIENT_POINT_OF_CONTACT_PHONE";
export const CHANGE_CLIENT_POINT_OF_CONTACT_EMAIL = "CHANGE_CLIENT_POINT_OF_CONTACT_EMAIL";
export const LOAD_CLIENT_DETAILS_SUCCESS = "LOAD_CLIENT_DETAILS_SUCCESS";
export const LOAD_CLIENT_DETAILS_ERROR = "LOAD_CLIENT_DETAILS_ERROR";
export const LOAD_CLIENT_DETAILS_REQUEST = "LOAD_CLIENT_DETAILS_REQUEST";