export const CHANGE_TIME = "CHANGE_TIME";
export const CHANGE_DATE = "CHANGE_DATE";
export const CHANGE_ACTIVITY = "CHANGE_ACTIVITY";
export const UPDATE_ACTIVITY_REQUEST = "UPDATE_ACTIVITY_REQUEST";
export const LOAD_ALL_MY_ACTIVITY_LOGS = "LOAD_ALL_MY_ACTIVITY_LOGS";
export const LOAD_ALL_MY_ACTIVITY_LOGS_REQUEST = "LOAD_ALL_MY_ACTIVITY_LOGS_REQUEST";
