export const LOAD_CASE_INFO_REQUEST = "LOAD_CASE_INFO_REQUEST";
export const LOAD_CASE_INFO_ERROR = "LOAD_CASE_INFO_ERROR";
export const LOAD_CASE_INFO_SUCCESS = "LOAD_CASE_INFO_SUCCESS";

export const LOAD_SECTIONS_REQUEST = "LOAD_SECTIONS_REQUEST";
export const LOAD_SECTIONS_ERROR = "LOAD_SECTIONS_ERROR";
export const LOAD_SECTIONS_SUCCESS = "LOAD_SECTIONS_SUCCESS";

export const LOAD_INVESTIGATOR_INFO_REQUEST = "LOAD_INVESTIGATOR_INFO_REQUEST";
export const LOAD_INVESTIGATOR_INFO_SUCCESS = "LOAD_INVESTIGATOR_INFO_SUCCESS";
export const LOAD_INVESTIGATOR_INFO_ERROR = "LOAD_INVESTIGATOR_INFO_ERROR";