export const NEW_CLIENT_REQUEST = "NEW_CLIENT_REQUEST";
export const NEW_CLIENT_SUCCESS = "NEW_CLIENT_SUCCESS";
export const NEW_CLIENT_ERROR = "NEW_CLIENT_ERROR";

export const CHANGE_CLIENT_FIRST_NAME = "CHANGE_CLIENT_FIRST_NAME";
export const CHANGE_CLIENT_LAST_NAME = "CHANGE_CLIENT_LAST_NAME";
export const CHANGE_CLIENT_USERNAME = "CHANGE_CLIENT_USERNAME";
export const CHANGE_CLIENT_EMAIL = "CHANGE_CLIENT_EMAIL";
export const CHANGE_CLIENT_PASSWORD = "CHANGE_CLIENT_PASSWORD";

export const CHANGE_CLIENT_POINT_OF_CONTACT_NAME = "CHANGE_CLIENT_POINT_OF_CONTACT_NAME";
export const CHANGE_CLIENT_POINT_OF_CONTACT_PHONE = "CHANGE_CLIENT_POINT_OF_CONTACT_PHONE";
export const CHANGE_CLIENT_POINT_OF_CONTACT_EMAIL = "CHANGE_CLIENT_POINT_OF_CONTACT_EMAIL";