export const VERIFY_CODE_REQUEST = "VERIFY_CODE_REQUEST";
export const VERIFY_CODE_ERROR = "VERIFY_CODE_ERROR";
export const VERIFY_CODE_SUCCESS = "VERIFY_CODE_SUCCESS";

export const GET_NEW_CODE_REQUEST = "GET_NEW_CODE_REQUEST";
export const GET_NEW_CODE_ERROR = "GET_NEW_CODE_ERROR";
export const GET_NEW_CODE_SUCCESS = "GET_NEW_CODE_SUCCESS";