export const LOAD_ALL_CASES_REQUEST = "LOAD_ALL_CASES_REQUEST";
export const LOAD_ALL_CASES_ERROR = "LOAD_ALL_CASES_ERROR";
export const LOAD_ALL_CASES_SUCCESS = "LOAD_ALL_CASES_SUCCESS";

export const LOAD_SECTIONS_REQUEST = "LOAD_SECTIONS_REQUEST";
export const LOAD_SECTIONS_ERROR = "LOAD_SECTIONS_ERROR";
export const LOAD_SECTIONS_SUCCESS = "LOAD_SECTIONS_SUCCESS";
