export const RESET_REQUESTING = "RESET_REQUESTING";
export const RESET_ERROR = "RESET_ERROR";
export const RESET_SUCCESS = "RESET_SUCCESS";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_CONFIRM_PASSWORD = "CHANGE_CONFIRM_PASSWORD";
export const CHANGE_UUID = "CHANGE_UUID";
