export const CHANGE_TIME = "CHANGE_TIME";
export const CHANGE_DATE = "CHANGE_DATE";
export const CHANGE_ACTIVITY = "CHANGE_ACTIVITY";

export const NEW_ACTIVITY_REQUEST = "NEW_ACTIVITY_REQUEST";
export const NEW_ACTIVITY_SUCCESS = "NEW_ACTIVITY_SUCCESS";
export const NEW_ACTIVITY_ERROR = "NEW_ACTIVITY_ERROR";

export const LOAD_ALL_MY_ACTIVITY_LOGS = "LOAD_ALL_MY_ACTIVITY_LOGS";
export const LOAD_ALL_MY_ACTIVITY_LOGS_REQUEST = "LOAD_ALL_MY_ACTIVITY_LOGS_REQUEST";
