export const LOAD_ALL_CLIENT = "LOAD_ALL_CLIENT";
export const LOAD_ALL_CLIENT_REQUEST = "LOAD_ALL_CLIENT_REQUEST";
export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_ERROR = "DELETE_CLIENT_ERROR";
