export const CLIENT_DOWNLOAD_REPORT_REQUEST = "CLIENT_DOWNLOAD_REPORT_REQUEST";
export const CLIENT_DOWNLOAD_REPORT_SUCCESS = "CLIENT_DOWNLOAD_REPORT_SUCCESS";
export const CLIENT_DOWNLOAD_REPORT_ERROR = "CLIENT_DOWNLOAD_REPORT_ERROR";

export const LOAD_ALL_REPORT_REQUEST = "LOAD_ALL_REPORT_REQUEST";
export const LOAD_ALL_REPORT = "LOAD_ALL_REPORT";
export const LOAD_ALL_REPORT_ERROR = "LOAD_ALL_REPORT_ERROR";

