export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_ERROR = "EDIT_PROFILE_ERROR";
export const LOAD_INVESTIGATOR_INFO_REQUEST = "LOAD_INVESTIGATOR_INFO_REQUEST";
export const LOAD_INVESTIGATOR_INFO = "LOAD_INVESTIGATOR_INFO";