export const LOAD_ALL_MY_ACTIVITY_LOGS = "LOAD_ALL_MY_ACTIVITY_LOGS";
export const LOAD_ALL_MY_ACTIVITY_LOGS_REQUEST = "LOAD_ALL_MY_ACTIVITY_LOGS_REQUEST";
export const DELETE_ACTIVITY_REQUEST = "DELETE_ACTIVITY_REQUEST";
export const START_DATE = "START_DATE";
export const END_DATE = "END_DATE";
export const APPLY_FILTER = "APPLY_FILTER";
