export const EDIT_CASE_REQUESTING = "EDIT_CASE_REQUESTING";
export const EDIT_CASE_SUCCESS = "EDIT_CASE_SUCCESS";
export const EDIT_CASE_ERROR = "EDIT_CASE_ERROR";

export const EDIT_LOAD_CLIENTS_REQUEST = "EDIT_LOAD_CLIENTS_REQUEST";
export const EDIT_LOAD_CLIENTS_SUCCESS = "EDIT_LOAD_CLIENTS_SUCCESS";
export const EDIT_LOAD_CLIENTS_ERROR = "EDIT_LOAD_CLIENTS_ERROR";

export const EDIT_LOAD_CASE_REQUESTING = "EDIT_LOAD_CASE_REQUESTING";
export const EDIT_LOAD_CASE_SUCCESS = "EDIT_LOAD_CASE_SUCCESS";
export const EDIT_LOAD_CASE_ERROR = "EDIT_LOAD_CASE_ERROR";
