export const REGISTER_REQUESTING = "REGISTER_REQUESTING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const CHANGE_FIRSTNAME = "CHANGE_FIRSTNAME";
export const CHANGE_LASTNAME = "CHANGE_LASTNAME";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_CONFIRM_PASSWORD = "CHANGE_CONFIRM_PASSWORD";
export const CHANGE_USERNAME = "CHANGE_USERNAME";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_LICENSEID = "CHANGE_LICENSEID";
export const CHANGE_UBI = "CHANGE_UBI";
export const CHANGE_PHOTO = "CHANGE_PHOTO";
export const CHANGE_PHONE = "CHANGE_PHONE";
export const CHANGE_AGENCY_NAME = "CHANGE_AGENCY_NAME";
export const CHANGE_AGENCY_ADDRESS = "CHANGE_AGENCY_ADDRESS";
export const CHANGE_AGENCY_CITY = "CHANGE_AGENCY_CITY";
export const CHANGE_AGENCY_STATE = "CHANGE_AGENCY_STATE";
export const CHANGE_AGENCY_ZIP_CODE = "CHANGE_AGENCY_ZIP_CODE";
export const CHANGE_AGENCY_FAX = "CHANGE_AGENCY_FAX";
export const CHANGE_AGENCY_LOGO = "CHANGE_AGENCY_LOGO";
export const CHANGE_AGENCY_IS_MEMBER_OF_ASSOCIATION = "CHANGE_AGENCY_IS_MEMBER_OF_ASSOCIATION";
export const CHANGE_DESCRIPTION = "CHANGE_DESCRIPTION";

export const UPLOAD_PHOTO_REQUEST = "UPLOAD_PHOTO_REQUEST";
export const UPLOAD_PHOTO_PROGRESS = "UPLOAD_PHOTO_PROGRESS";
export const UPLOAD_PHOTO_SUCCESS = "UPLOAD_PHOTO_SUCCESS";
export const UPLOAD_PHOTO_FAILURE = "UPLOAD_PHOTO_FAILURE";

export const UPLOAD_AGENCY_LOGO_REQUEST = "UPLOAD_AGENCY_LOGO_REQUEST";
export const UPLOAD_AGENCY_LOGO_PROGRESS = "UPLOAD_AGENCY_LOGO_PROGRESS";
export const UPLOAD_AGENCY_LOGO_SUCCESS = "UPLOAD_AGENCY_LOGO_SUCCESS";
export const UPLOAD_AGENCY_LOGO_FAILURE = "UPLOAD_AGENCY_LOGO_FAILURE";

export const STEP_ONE_REQUEST = "STEP_ONE_REQUEST";
export const STEP_ONE_SUCCESS = "STEP_ONE_SUCCESS";
export const STEP_ONE_FAIL = "STEP_ONE_FAIL";

export const STEP_TWO_REQUEST = "STEP_TWO_REQUEST";
export const STEP_TWO_SUCCESS = "STEP_TWO_SUCCESS";
export const STEP_TWO_FAIL = "STEP_TWO_FAIL";

export const STEP_THREE_REQUEST = "STEP_THREE_REQUEST";
export const STEP_THREE_FAIL = "STEP_THREE_FAIL";
export const STEP_THREE_SUCCESS = "STEP_THREE_SUCCESS";

export const STEP_REFRESH = "STEP_REFRESH";
export const GO_TO_PREVIOUS_STEP = "GO_TO_PREVIOUS_STEP";

export const STEP_FOUR = "STEP_FOUR";
export const SUBMIT_FORM_DATA = "SUBMIT_FORM_DATA";
export const PENDING = "PENDING";
export const SUCCESS = "SUCCESS";
export const FAILED = "FAILED";
