export const LOAD_ALL_REPORT = "LOAD_ALL_REPORT";
export const CASE_LIST_REQUEST = "CASE_LIST_REQUEST";
export const LOAD_ALL_REPORT_REQUEST = "LOAD_ALL_REPORT_REQUEST";
export const DELETE_REPORT_REQUEST = "DELETE_REPORT_REQUEST";

export const CLIENT_DOWNLOAD_REPORT_REQUEST = "CLIENT_DOWNLOAD_REPORT_REQUEST";
export const CLIENT_DOWNLOAD_REPORT_SUCCESS = "CLIENT_DOWNLOAD_REPORT_SUCCESS";
export const CLIENT_DOWNLOAD_REPORT_ERROR = "CLIENT_DOWNLOAD_REPORT_ERROR";

export const GIVE_CLIENT_ACCESS = "GIVE_CLIENT_ACCESS";
export const GIVE_CLIENT_ACCESS_SUCCESS = "GIVE_CLIENT_ACCESS_SUCCESS";
export const GIVE_CLIENT_ACCESS_ERROR = "GIVE_CLIENT_ACCESS_ERROR";

export const START_DATE = "START_DATE";
export const END_DATE = "END_DATE";
export const APPLY_FILTER = "APPLY_FILTER";
export const LOAD_FILTER_REQUEST = "LOAD_FILTER_REQUEST";
export const LOAD_ALL_FILTER = "LOAD_ALL_FILTER";
export const FILTER_BY_PARAM_REQUEST = "FILTER_BY_PARAM_REQUEST";